app_index:
    pattern:  /
    defaults: { _controller: WtsdaAppBundle:Default:index }

app_news:
    pattern:  /news/
    defaults: { _controller: WtsdaAppBundle:News:index }

app_events:
    pattern: /events/
    defaults: { _controller: WtsdaAppBundle:Events:index }

app_dojangs:
    pattern: /dojangs/
    defaults: { _controller: WtsdaAppBundle:Dojangs:index }

app_scholarship:
    pattern: /scholarship/
    defaults: { _controller: WtsdaAppBundle:Scholarship:index }

app_media:
    pattern: /media/
    defaults: { _controller: WtsdaAppBundle:Media:index }

app_about:
    pattern: /about/
    defaults: { _controller: WtsdaAppBundle:About:index }
