parameters:
#    wtsda_app.example.class: Wtsda\AppBundle\Example

services:
#    wtsda_app.example:
#        class: %wtsda_app.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
