parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     ~
    database_name:     wtsda
    database_user:     bob
    database_password: f1R381rd

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en_US
    secret:            ThisTokenIsNotSoSecretChangeIt
