parameters:
#    wtsda_admin.example.class: Wtsda\AdminBundle\Example

services:
#    wtsda_admin.example:
#        class: %wtsda_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
