parameters:
#    wtsda_core.example.class: Wtsda\CoreBundle\Example

services:
#    wtsda_core.example:
#        class: %wtsda_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
